### ISSUE TITLE
Arabic-En extension

### ISSUE THREAD

**Issue by GokulNC** [subins2000/indicen#14]
Hii @subins2000 

Thanks for making this extension, it's very helpful!
I made a fork of your code for romanizing Arabic texts (by just replacing IndicJS transliterator with a custom one).

Here is the source code:
https://github.com/GokulNC/Arabic-Romanizer-Web-Extension
(BTW, I am not a web developer, so I might not have followed good practices)

I have also published it on Chrome Store, and added credits to you wherever possible.

I just wanted to create this issue to thank you for making this awesome tool :)
And also please let me know if you have any concerns about this, or any suggestions are also welcome!
(Please feel free to close this issue once ack'ed)

**Comment by subins2000** [comment]
Awesome! Happy to know that this extension has been forked for other languages too! Thank you for letting me know <3
